all:
	g++ *.cpp -o raytracer -std=c++11 -O3
r:
	./raytracer ../test_scenes/inputs/simple.xml
c:
	./raytracer ../test_scenes/inputs/cornellbox.xml
s:
	./raytracer ../test_scenes/inputs/simple_reflectance.xml
